[package]
name = "testing1"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
novu = { path = "../../" }
serde_json = "1.0.87"
